<?php
/**
 * @file
 * glazed_main_theme_settings.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_main_theme_settings_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_about-me:uuid/node/09c313be-63ee-4325-a474-12ea5c8792db.
  $menu_links['main-menu_about-me:uuid/node/09c313be-63ee-4325-a474-12ea5c8792db'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/09c313be-63ee-4325-a474-12ea5c8792db',
    'router_path' => 'uuid',
    'link_title' => 'About Me',
    'options' => array(
      'identifier' => 'main-menu_about-me:uuid/node/09c313be-63ee-4325-a474-12ea5c8792db',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '09c313be-63ee-4325-a474-12ea5c8792db',
    'vuuid' => '3c134e49-d6e2-4bb4-bce0-113de70bea96',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_about-us-timeline:uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495.
  $menu_links['main-menu_about-us-timeline:uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495',
    'router_path' => 'uuid',
    'link_title' => 'About Us Timeline',
    'options' => array(
      'identifier' => 'main-menu_about-us-timeline:uuid/node/fefb9dcc-281b-4544-b7e0-4dfaa4ebf495',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'fefb9dcc-281b-4544-b7e0-4dfaa4ebf495',
    'vuuid' => '779a9363-7b1e-4a18-81a7-186ef1fc6b96',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_about-us:uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776.
  $menu_links['main-menu_about-us:uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776',
    'router_path' => 'uuid',
    'link_title' => 'About Us',
    'options' => array(
      'identifier' => 'main-menu_about-us:uuid/node/984cfc78-e4cc-4262-9452-20b267bd3776',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '984cfc78-e4cc-4262-9452-20b267bd3776',
    'vuuid' => 'e93aa9a8-0aec-4cc3-93d9-d730ec29d238',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc.
  $menu_links['main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    'router_path' => 'uuid',
    'link_title' => 'Animation Engine',
    'options' => array(
      'identifier' => 'main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '34998698-bc3b-4056-a6b6-b793443a2edc',
    'vuuid' => '27e06c20-3cb1-4fd2-8e2d-07119376340f',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0.
  $menu_links['main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'router_path' => 'uuid',
    'link_title' => 'Blockquote',
    'options' => array(
      'identifier' => 'main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'vuuid' => '9d51645b-eda3-40b6-8a26-041bd84ee719',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_blog-classic-style:blog.
  $menu_links['main-menu_blog-classic-style:blog'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog',
    'router_path' => 'blog',
    'link_title' => 'Blog Classic Style',
    'options' => array(
      'identifier' => 'main-menu_blog-classic-style:blog',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-grid-2-columns:blog/grid2.
  $menu_links['main-menu_blog-grid-2-columns:blog/grid2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/grid2',
    'router_path' => 'blog/grid2',
    'link_title' => 'Blog Grid 2 Columns',
    'options' => array(
      'identifier' => 'main-menu_blog-grid-2-columns:blog/grid2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-grid-3-columns:blog/grid3.
  $menu_links['main-menu_blog-grid-3-columns:blog/grid3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/grid3',
    'router_path' => 'blog/grid3',
    'link_title' => 'Blog Grid 3 Columns',
    'options' => array(
      'identifier' => 'main-menu_blog-grid-3-columns:blog/grid3',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-grid-4-columns:blog/grid4.
  $menu_links['main-menu_blog-grid-4-columns:blog/grid4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/grid4',
    'router_path' => 'blog/grid4',
    'link_title' => 'Blog Grid 4 Columns',
    'options' => array(
      'identifier' => 'main-menu_blog-grid-4-columns:blog/grid4',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-gridstack:blog/gridstack.
  $menu_links['main-menu_blog-gridstack:blog/gridstack'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/gridstack',
    'router_path' => 'blog/gridstack',
    'link_title' => 'Blog GridStack',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_blog-gridstack:blog/gridstack',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog-modern-style:blog/modern.
  $menu_links['main-menu_blog-modern-style:blog/modern'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog/modern',
    'router_path' => 'blog/modern',
    'link_title' => 'Blog Modern Style',
    'options' => array(
      'identifier' => 'main-menu_blog-modern-style:blog/modern',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_blog:blog',
  );
  // Exported menu link: main-menu_blog:blog.
  $menu_links['main-menu_blog:blog'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'blog',
    'router_path' => 'blog',
    'link_title' => 'Blog',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_blog:blog',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: main-menu_box-header:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73.
  $menu_links['main-menu_box-header:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    'router_path' => 'uuid',
    'link_title' => 'Box Header',
    'options' => array(
      'identifier' => 'main-menu_box-header:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'f9deb576-445f-4b2b-914b-930fc84dcf73',
    'vuuid' => 'bedbf833-2b07-453d-a899-d653134d678f',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb.
  $menu_links['main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    'router_path' => 'uuid',
    'link_title' => 'Buttons',
    'options' => array(
      'identifier' => 'main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '34d13068-3849-4eaf-89d4-880954ac8bdb',
    'vuuid' => '10201af7-9331-4407-94b1-64313b6bb59f',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea.
  $menu_links['main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea',
    'router_path' => 'uuid',
    'link_title' => 'Call to Action',
    'options' => array(
      'identifier' => 'main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'a13b4055-cfd9-4437-9127-35acd06cf9ea',
    'vuuid' => 'f69d5841-c705-409e-8a5b-6c2d9703926f',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Carousel Element',
    'options' => array(
      'identifier' => 'main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => '4f317f99-58ab-4cd8-a61e-62fa569e37c2',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_centered-inline:uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4.
  $menu_links['main-menu_centered-inline:uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4',
    'router_path' => 'uuid',
    'link_title' => 'Centered (Inline)',
    'options' => array(
      'identifier' => 'main-menu_centered-inline:uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4',
    'vuuid' => '9f621201-fcf1-46b9-a1a9-bf494ff1faa1',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_centered-stacked:uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50.
  $menu_links['main-menu_centered-stacked:uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50',
    'router_path' => 'uuid',
    'link_title' => 'Centered (Stacked)',
    'options' => array(
      'identifier' => 'main-menu_centered-stacked:uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '2efc8ede-fe27-42f4-b1a9-aa20c164ab50',
    'vuuid' => '99f5ee35-4ae9-4c56-b398-51208b848325',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f.
  $menu_links['main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    'router_path' => 'uuid',
    'link_title' => 'Circle Counter',
    'options' => array(
      'identifier' => 'main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    'vuuid' => 'e7da6862-5e7f-4527-9833-0251f3bf641d',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99.
  $menu_links['main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'router_path' => 'uuid',
    'link_title' => 'Collapsibles',
    'options' => array(
      'identifier' => 'main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'vuuid' => '8b9dd72e-9135-4ee3-8842-6c388f39874e',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92.
  $menu_links['main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    'router_path' => 'uuid',
    'link_title' => 'Colored Icon Boxes',
    'options' => array(
      'identifier' => 'main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '4e840855-52c9-47a4-9f74-80fb2734dd92',
    'vuuid' => '31e1518f-750a-4db5-8ccb-b80e8b5c01b8',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a.
  $menu_links['main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'router_path' => 'uuid',
    'link_title' => 'Columns',
    'options' => array(
      'identifier' => 'main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'vuuid' => '000f9925-4da0-4a8a-909a-181a09db5deb',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_contact:contact.
  $menu_links['main-menu_contact:contact'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'contact',
    'router_path' => 'contact',
    'link_title' => 'Contact',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_contact:contact',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb.
  $menu_links['main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'router_path' => 'uuid',
    'link_title' => 'Content Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'vuuid' => '30307446-ee14-43ba-99c8-65e2e86cdfce',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829.
  $menu_links['main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9e718e9f-d297-46a8-a908-142b3853d829',
    'router_path' => 'uuid',
    'link_title' => 'Count Down Timer',
    'options' => array(
      'identifier' => 'main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '9e718e9f-d297-46a8-a908-142b3853d829',
    'vuuid' => '13db1943-9e84-40e0-9ef4-bbceedac4cde',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33.
  $menu_links['main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    'router_path' => 'uuid',
    'link_title' => 'Counter',
    'options' => array(
      'identifier' => 'main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    'vuuid' => '95a4d988-0946-4d86-9c09-6045d6d1d7ed',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_custom-colors:uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4.
  $menu_links['main-menu_custom-colors:uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4',
    'router_path' => 'uuid',
    'link_title' => 'Custom Colors',
    'options' => array(
      'identifier' => 'main-menu_custom-colors:uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'c52c1f98-2302-4133-9d8c-811d45a7f4b4',
    'vuuid' => '0fe4d939-d62a-42dc-8804-b0e2cf375c56',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_details-bottom:uuid/node/0fbc0438-4983-48b7-9ff1-eb3905dbfc05.
  $menu_links['main-menu_details-bottom:uuid/node/0fbc0438-4983-48b7-9ff1-eb3905dbfc05'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0fbc0438-4983-48b7-9ff1-eb3905dbfc05',
    'router_path' => 'uuid',
    'link_title' => 'Details Bottom',
    'options' => array(
      'identifier' => 'main-menu_details-bottom:uuid/node/0fbc0438-4983-48b7-9ff1-eb3905dbfc05',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '0fbc0438-4983-48b7-9ff1-eb3905dbfc05',
    'vuuid' => '9ce13cd7-0838-42ba-a2fb-a5b11b8eec9b',
    'parent_identifier' => 'main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
  );
  // Exported menu link: main-menu_details-left:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42.
  $menu_links['main-menu_details-left:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
    'router_path' => 'uuid',
    'link_title' => 'Details Left',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_details-left:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'uuid' => '66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
    'vuuid' => 'ae4a1659-1ee3-41e7-a173-13498a579da4',
    'parent_identifier' => 'main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
  );
  // Exported menu link: main-menu_details-right:uuid/node/2a8af362-8cce-4365-b01d-8df64bb71829.
  $menu_links['main-menu_details-right:uuid/node/2a8af362-8cce-4365-b01d-8df64bb71829'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2a8af362-8cce-4365-b01d-8df64bb71829',
    'router_path' => 'uuid',
    'link_title' => 'Details Right',
    'options' => array(
      'identifier' => 'main-menu_details-right:uuid/node/2a8af362-8cce-4365-b01d-8df64bb71829',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '2a8af362-8cce-4365-b01d-8df64bb71829',
    'vuuid' => 'ede1ad6d-a7c0-4afd-bdf5-699dfefef9a1',
    'parent_identifier' => 'main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
  );
  // Exported menu link: main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd.
  $menu_links['main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    'router_path' => 'uuid',
    'link_title' => 'Divider',
    'options' => array(
      'identifier' => 'main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '0825174b-b312-41f9-b2f6-64d4c22edefd',
    'vuuid' => 'a0547b7d-c341-4be7-ba40-514f7f3ac5bb',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640.
  $menu_links['main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640',
    'router_path' => 'uuid',
    'link_title' => 'Drop Shadow',
    'options' => array(
      'identifier' => 'main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '88d22be5-b9e3-4953-b98b-9c2deac33640',
    'vuuid' => '15e94fea-2838-4e64-a063-94952b349a0c',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4.
  $menu_links['main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/621b040c-215e-4302-a133-ee52589bf8c4',
    'router_path' => 'uuid',
    'link_title' => 'Drupal Blocks',
    'options' => array(
      'identifier' => 'main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '621b040c-215e-4302-a133-ee52589bf8c4',
    'vuuid' => 'dc162bc5-a2e2-4dc3-bbff-73b1817d2955',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d.
  $menu_links['main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d',
    'router_path' => 'uuid',
    'link_title' => 'Drupal Views',
    'options' => array(
      'identifier' => 'main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '8a6234be-e970-4c98-8074-daeda9957d3d',
    'vuuid' => 'e70ae525-044c-4fc7-ae9c-aeec810a9085',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Elements',
    'options' => array(
      'identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => '4f317f99-58ab-4cd8-a61e-62fa569e37c2',
  );
  // Exported menu link: main-menu_events:events.
  $menu_links['main-menu_events:events'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'events',
    'router_path' => 'events',
    'link_title' => 'Events',
    'options' => array(
      'identifier' => 'main-menu_events:events',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_faq:uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f.
  $menu_links['main-menu_faq:uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f',
    'router_path' => 'uuid',
    'link_title' => 'FAQ',
    'options' => array(
      'identifier' => 'main-menu_faq:uuid/node/973e2a11-c838-4666-a29c-49487ee8c79f',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '973e2a11-c838-4666-a29c-49487ee8c79f',
    'vuuid' => '162b4d89-6a14-47b0-98b9-11ddf3e7480b',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_floating-menu-header:uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56.
  $menu_links['main-menu_floating-menu-header:uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56',
    'router_path' => 'uuid',
    'link_title' => 'Floating Menu Header',
    'options' => array(
      'identifier' => 'main-menu_floating-menu-header:uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a5b033a1-c69c-4bc0-b645-23a0658efb56',
    'vuuid' => '4e4b3de7-d9e9-4366-96f7-c317135c06a6',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_full-width-header:uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac.
  $menu_links['main-menu_full-width-header:uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac',
    'router_path' => 'uuid',
    'link_title' => 'Full Width Header',
    'options' => array(
      'identifier' => 'main-menu_full-width-header:uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '2b1a92c8-69d9-494b-8db2-d588f8a012ac',
    'vuuid' => '2067eef7-9923-469e-9d00-8e0b450e1bf1',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_glazed-filter-no-spacing:portfolio/filter1.
  $menu_links['main-menu_glazed-filter-no-spacing:portfolio/filter1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/filter1',
    'router_path' => 'portfolio/filter1',
    'link_title' => 'Glazed Filter No Spacing',
    'options' => array(
      'identifier' => 'main-menu_glazed-filter-no-spacing:portfolio/filter1',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:portfolio/filter2',
  );
  // Exported menu link: main-menu_glazed-filter-with-spacing:portfolio/filter2.
  $menu_links['main-menu_glazed-filter-with-spacing:portfolio/filter2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/filter2',
    'router_path' => 'portfolio/filter2',
    'link_title' => 'Glazed Filter With Spacing',
    'options' => array(
      'identifier' => 'main-menu_glazed-filter-with-spacing:portfolio/filter2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:portfolio/filter2',
  );
  // Exported menu link: main-menu_glazed-full-screen-modal-portfolio:portfolio/modal2.
  $menu_links['main-menu_glazed-full-screen-modal-portfolio:portfolio/modal2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/modal2',
    'router_path' => 'portfolio/modal2',
    'link_title' => 'Glazed Full Screen Modal Portfolio',
    'options' => array(
      'identifier' => 'main-menu_glazed-full-screen-modal-portfolio:portfolio/modal2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:portfolio/filter2',
  );
  // Exported menu link: main-menu_glazed-inline-modal-portfolio:portfolio/modal1.
  $menu_links['main-menu_glazed-inline-modal-portfolio:portfolio/modal1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/modal1',
    'router_path' => 'portfolio/modal1',
    'link_title' => 'Glazed Inline Modal Portfolio',
    'options' => array(
      'identifier' => 'main-menu_glazed-inline-modal-portfolio:portfolio/modal1',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:portfolio/filter2',
  );
  // Exported menu link: main-menu_glazed-lightbox-portfolio:portfolio/lightbox.
  $menu_links['main-menu_glazed-lightbox-portfolio:portfolio/lightbox'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/lightbox',
    'router_path' => 'portfolio/lightbox',
    'link_title' => 'Glazed Lightbox Portfolio',
    'options' => array(
      'identifier' => 'main-menu_glazed-lightbox-portfolio:portfolio/lightbox',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_premium-portfolio:portfolio/filter2',
  );
  // Exported menu link: main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32.
  $menu_links['main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32',
    'router_path' => 'uuid',
    'link_title' => 'Google Maps',
    'options' => array(
      'identifier' => 'main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a4608e7f-a620-4b47-b9a6-3e960302cf32',
    'vuuid' => 'f03d4026-40fa-4216-b176-04b996df399e',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_grid-portfolio:<nolink>.
  $menu_links['main-menu_grid-portfolio:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Grid Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_grid-portfolio:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_portfolio:portfolio',
  );
  // Exported menu link: main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b.
  $menu_links['main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'router_path' => 'uuid',
    'link_title' => 'GridStack View',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'vuuid' => 'd53f2613-1bef-46c2-8fff-06d033b4f9e3',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095.
  $menu_links['main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    'router_path' => 'uuid',
    'link_title' => 'Header Layouts',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '7288000a-d02b-4ffa-96df-0029ffcfc095',
    'vuuid' => '33486959-44f8-4f11-8311-1233cb0c1840',
    'parent_identifier' => 'main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
  );
  // Exported menu link: main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73.
  $menu_links['main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    'router_path' => 'uuid',
    'link_title' => 'Header Styles',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'f9deb576-445f-4b2b-914b-930fc84dcf73',
    'vuuid' => 'bedbf833-2b07-453d-a899-d653134d678f',
    'parent_identifier' => 'main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
  );
  // Exported menu link: main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71.
  $menu_links['main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    'router_path' => 'uuid',
    'link_title' => 'Headers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '51bb3421-2cc2-42b4-b278-5e845db02e71',
    'vuuid' => '1f892124-120f-4ffd-8f73-5bf4815ac91a',
  );
  // Exported menu link: main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917.
  $menu_links['main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'router_path' => 'uuid',
    'link_title' => 'Home App Landing Page',
    'options' => array(
      'identifier' => 'main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'vuuid' => 'd05901a4-742b-4a90-92da-f4c6bb044789',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6.
  $menu_links['main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'router_path' => 'uuid',
    'link_title' => 'Home Basic',
    'options' => array(
      'identifier' => 'main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'vuuid' => '3414de34-5b3f-4cf5-b7e2-58b19e6c2e96',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35.
  $menu_links['main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'router_path' => 'uuid',
    'link_title' => 'Home Blog Classic',
    'options' => array(
      'identifier' => 'main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'vuuid' => '0970000a-ab60-4be4-a902-9c16ce784d8d',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825.
  $menu_links['main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    'router_path' => 'uuid',
    'link_title' => 'Home Business Clean',
    'options' => array(
      'identifier' => 'main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '760f2195-e3fd-4957-ac92-410530f39825',
    'vuuid' => '30b2149e-b56c-4982-82ca-29b5ab313664',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd.
  $menu_links['main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    'router_path' => 'uuid',
    'link_title' => 'Home Canvas',
    'options' => array(
      'identifier' => 'main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '2bc7e0bd-0597-455f-9730-a058acce07dd',
    'vuuid' => '2fff4c8c-8d30-4465-9564-59464b4ac769',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4.
  $menu_links['main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    'router_path' => 'uuid',
    'link_title' => 'Home Main Demo',
    'options' => array(
      'identifier' => 'main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => 'c8982be9-90c8-4813-ad2d-87c0934213e4',
    'vuuid' => 'ce9f1ef0-d03d-40b2-a4d0-2efff86b8ef8',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_homepage-portfolio-1:uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf.
  $menu_links['main-menu_homepage-portfolio-1:uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf',
    'router_path' => 'uuid',
    'link_title' => 'Homepage Portfolio 1',
    'options' => array(
      'identifier' => 'main-menu_homepage-portfolio-1:uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'f58f6881-0aef-4492-ad3b-c03be4cc29cf',
    'vuuid' => '66c71638-091c-42d1-a3e0-a5f7fd78a96b',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6.
  $menu_links['main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'router_path' => 'uuid',
    'link_title' => 'Homepages',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'vuuid' => '3414de34-5b3f-4cf5-b7e2-58b19e6c2e96',
  );
  // Exported menu link: main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb.
  $menu_links['main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'router_path' => 'uuid',
    'link_title' => 'Icon Box',
    'options' => array(
      'identifier' => 'main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'vuuid' => '30307446-ee14-43ba-99c8-65e2e86cdfce',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd.
  $menu_links['main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    'router_path' => 'uuid',
    'link_title' => 'Icon Well',
    'options' => array(
      'identifier' => 'main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '5ff84c19-e9e1-4760-9253-abbedce064cd',
    'vuuid' => 'a6e06b21-7e59-4e91-afdc-db80b8cc7130',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598.
  $menu_links['main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    'router_path' => 'uuid',
    'link_title' => 'Icons',
    'options' => array(
      'identifier' => 'main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    'vuuid' => '91ffc379-aabf-4968-acd2-7f501c6242d7',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_image-compare:uuid/node/3fbdac22-c64d-4065-941d-9b19a805d2de.
  $menu_links['main-menu_image-compare:uuid/node/3fbdac22-c64d-4065-941d-9b19a805d2de'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/3fbdac22-c64d-4065-941d-9b19a805d2de',
    'router_path' => 'uuid',
    'link_title' => 'Image Compare',
    'options' => array(
      'identifier' => 'main-menu_image-compare:uuid/node/3fbdac22-c64d-4065-941d-9b19a805d2de',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '3fbdac22-c64d-4065-941d-9b19a805d2de',
    'vuuid' => 'cd92beda-71e6-433f-8213-30134d9c6fa7',
    'parent_identifier' => 'main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
  );
  // Exported menu link: main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94.
  $menu_links['main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    'router_path' => 'uuid',
    'link_title' => 'Image Element & Slider',
    'options' => array(
      'identifier' => 'main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    'vuuid' => '2a328cfd-68fe-4a3c-bb01-fb8d27bc2ce0',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc.
  $menu_links['main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    'router_path' => 'uuid',
    'link_title' => 'Interactive Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '34998698-bc3b-4056-a6b6-b793443a2edc',
    'vuuid' => '27e06c20-3cb1-4fd2-8e2d-07119376340f',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2.
  $menu_links['main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'router_path' => 'uuid',
    'link_title' => 'Jumbotron',
    'options' => array(
      'identifier' => 'main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'vuuid' => '0d853e93-8b10-4a47-9e91-0945dfc1d684',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Layout Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => '4f317f99-58ab-4cd8-a61e-62fa569e37c2',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7.
  $menu_links['main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'router_path' => 'uuid',
    'link_title' => 'Lead',
    'options' => array(
      'identifier' => 'main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'vuuid' => '09d9502f-11ab-4811-9f75-0c85e32f95b2',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_lightbox-images:uuid/node/310ef199-cd73-4a38-8164-60a5058e6e5d.
  $menu_links['main-menu_lightbox-images:uuid/node/310ef199-cd73-4a38-8164-60a5058e6e5d'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/310ef199-cd73-4a38-8164-60a5058e6e5d',
    'router_path' => 'uuid',
    'link_title' => 'Lightbox Images',
    'options' => array(
      'identifier' => 'main-menu_lightbox-images:uuid/node/310ef199-cd73-4a38-8164-60a5058e6e5d',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '310ef199-cd73-4a38-8164-60a5058e6e5d',
    'vuuid' => '0de4efa5-1c18-4b1e-9682-2673d697cc9d',
    'parent_identifier' => 'main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
  );
  // Exported menu link: main-menu_logo-center-menu-left:uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648.
  $menu_links['main-menu_logo-center-menu-left:uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648',
    'router_path' => 'uuid',
    'link_title' => 'Logo Center, Menu Left',
    'options' => array(
      'identifier' => 'main-menu_logo-center-menu-left:uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '8c1594e4-5a78-4657-b6dc-26b40cf72648',
    'vuuid' => '9302f17f-6e9c-489b-8f8d-d540c4ab7bec',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_logo-center-menu-right:uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5.
  $menu_links['main-menu_logo-center-menu-right:uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5',
    'router_path' => 'uuid',
    'link_title' => 'Logo Center, Menu Right',
    'options' => array(
      'identifier' => 'main-menu_logo-center-menu-right:uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'f62f6d64-0a66-4d18-bbdc-692f0a946ac5',
    'vuuid' => '55b24ed2-26aa-4a24-a4f5-527cb27d9ce7',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_logo-left-menu-left:uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b.
  $menu_links['main-menu_logo-left-menu-left:uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b',
    'router_path' => 'uuid',
    'link_title' => 'Logo Left, Menu Left',
    'options' => array(
      'identifier' => 'main-menu_logo-left-menu-left:uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b',
    'vuuid' => 'a3cfde1a-07fc-4497-a0cf-508c1770a746',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_logo-right-menu-left:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095.
  $menu_links['main-menu_logo-right-menu-left:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    'router_path' => 'uuid',
    'link_title' => 'Logo Right, Menu Left',
    'options' => array(
      'identifier' => 'main-menu_logo-right-menu-left:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '7288000a-d02b-4ffa-96df-0029ffcfc095',
    'vuuid' => '33486959-44f8-4f11-8311-1233cb0c1840',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_masonry-portfolio:<nolink>.
  $menu_links['main-menu_masonry-portfolio:<nolink>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<nolink>',
    'router_path' => '<nolink>',
    'link_title' => 'Masonry Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_masonry-portfolio:<nolink>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_portfolio:portfolio',
  );
  // Exported menu link: main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c.
  $menu_links['main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'router_path' => 'uuid',
    'link_title' => 'Media Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'vuuid' => 'ece5eb5a-2680-494f-8721-bfe60da3f5ae',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456.
  $menu_links['main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456',
    'router_path' => 'uuid',
    'link_title' => 'Motion Image Box',
    'options' => array(
      'identifier' => 'main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '448c021f-1d62-43a3-aaa9-6111e2dca456',
    'vuuid' => '77bf69bc-816e-46e4-8355-f91dca7568c5',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_news:news.
  $menu_links['main-menu_news:news'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'news',
    'router_path' => 'news',
    'link_title' => 'News',
    'options' => array(
      'identifier' => 'main-menu_news:news',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_pages:events.
  $menu_links['main-menu_pages:events'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'events',
    'router_path' => 'events',
    'link_title' => 'Pages',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_pages:events',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902.
  $menu_links['main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'router_path' => 'uuid',
    'link_title' => 'Panel',
    'options' => array(
      'identifier' => 'main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'vuuid' => 'a8a4ab7a-1dd7-4a09-8124-df9313565876',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_portfolio-1-column-with-excerpt:portfolio/1excerpt.
  $menu_links['main-menu_portfolio-1-column-with-excerpt:portfolio/1excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/1excerpt',
    'router_path' => 'portfolio/1excerpt',
    'link_title' => 'Portfolio 1 Column with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-1-column-with-excerpt:portfolio/1excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-1-column:portfolio/1.
  $menu_links['main-menu_portfolio-1-column:portfolio/1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/1',
    'router_path' => 'portfolio/1',
    'link_title' => 'Portfolio 1 Column',
    'options' => array(
      'identifier' => 'main-menu_portfolio-1-column:portfolio/1',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-2-columns:portfolio/2.
  $menu_links['main-menu_portfolio-2-columns:portfolio/2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/2',
    'router_path' => 'portfolio/2',
    'link_title' => 'Portfolio 2 Columns',
    'options' => array(
      'identifier' => 'main-menu_portfolio-2-columns:portfolio/2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-3-columns:portfolio/3.
  $menu_links['main-menu_portfolio-3-columns:portfolio/3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/3',
    'router_path' => 'portfolio/3',
    'link_title' => 'Portfolio 3 Columns',
    'options' => array(
      'identifier' => 'main-menu_portfolio-3-columns:portfolio/3',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-4-columns:portfolio.
  $menu_links['main-menu_portfolio-4-columns:portfolio'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio',
    'router_path' => 'portfolio',
    'link_title' => 'Portfolio 4 Columns',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_portfolio-4-columns:portfolio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-6-columns:portfolio/6.
  $menu_links['main-menu_portfolio-6-columns:portfolio/6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/6',
    'router_path' => 'portfolio/6',
    'link_title' => 'Portfolio 6 Columns',
    'options' => array(
      'identifier' => 'main-menu_portfolio-6-columns:portfolio/6',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_grid-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-2-with-excerpt:portfolio/v2excerpt.
  $menu_links['main-menu_portfolio-masonry-2-with-excerpt:portfolio/v2excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v2excerpt',
    'router_path' => 'portfolio/v2excerpt',
    'link_title' => 'Portfolio Masonry 2 with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-2-with-excerpt:portfolio/v2excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-2:portfolio/v2.
  $menu_links['main-menu_portfolio-masonry-2:portfolio/v2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v2',
    'router_path' => 'portfolio/v2',
    'link_title' => 'Portfolio Masonry 2',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-2:portfolio/v2',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-3-with-excerpt:portfolio/v3excerpt.
  $menu_links['main-menu_portfolio-masonry-3-with-excerpt:portfolio/v3excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v3excerpt',
    'router_path' => 'portfolio/v3excerpt',
    'link_title' => 'Portfolio Masonry 3 with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-3-with-excerpt:portfolio/v3excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-3:portfolio/v3.
  $menu_links['main-menu_portfolio-masonry-3:portfolio/v3'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v3',
    'router_path' => 'portfolio/v3',
    'link_title' => 'Portfolio Masonry 3',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-3:portfolio/v3',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-4-with-excerpt:portfolio/v4excerpt.
  $menu_links['main-menu_portfolio-masonry-4-with-excerpt:portfolio/v4excerpt'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v4excerpt',
    'router_path' => 'portfolio/v4excerpt',
    'link_title' => 'Portfolio Masonry 4 with Excerpt',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-4-with-excerpt:portfolio/v4excerpt',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-4:portfolio/v4.
  $menu_links['main-menu_portfolio-masonry-4:portfolio/v4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v4',
    'router_path' => 'portfolio/v4',
    'link_title' => 'Portfolio Masonry 4',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-4:portfolio/v4',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-masonry-6:portfolio/v6.
  $menu_links['main-menu_portfolio-masonry-6:portfolio/v6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/v6',
    'router_path' => 'portfolio/v6',
    'link_title' => 'Portfolio Masonry 6',
    'options' => array(
      'identifier' => 'main-menu_portfolio-masonry-6:portfolio/v6',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_masonry-portfolio:<nolink>',
  );
  // Exported menu link: main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42.
  $menu_links['main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
    'router_path' => 'uuid',
    'link_title' => 'Portfolio Pages',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_portfolio-pages:uuid/node/66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '66705fa9-4a74-4b5d-ba68-5d4b2b441c42',
    'vuuid' => 'ae4a1659-1ee3-41e7-a173-13498a579da4',
    'parent_identifier' => 'main-menu_portfolio:portfolio',
  );
  // Exported menu link: main-menu_portfolio:portfolio.
  $menu_links['main-menu_portfolio:portfolio'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio',
    'router_path' => 'portfolio',
    'link_title' => 'Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_portfolio:portfolio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -45,
    'customized' => 1,
  );
  // Exported menu link: main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e.
  $menu_links['main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'router_path' => 'uuid',
    'link_title' => 'Positioned Layers',
    'options' => array(
      'identifier' => 'main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'vuuid' => '7a55bcf6-0342-4a53-a7a0-c57dcd6f735a',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_premium-portfolio:portfolio/filter2.
  $menu_links['main-menu_premium-portfolio:portfolio/filter2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'portfolio/filter2',
    'router_path' => 'portfolio/filter2',
    'link_title' => 'Premium Portfolio',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_premium-portfolio:portfolio/filter2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_portfolio:portfolio',
  );
  // Exported menu link: main-menu_pricing-page:uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2.
  $menu_links['main-menu_pricing-page:uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2',
    'router_path' => 'uuid',
    'link_title' => 'Pricing Page',
    'options' => array(
      'identifier' => 'main-menu_pricing-page:uuid/node/e9a73a03-7034-42a9-8a77-5ff90c98a0d2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'e9a73a03-7034-42a9-8a77-5ff90c98a0d2',
    'vuuid' => '513e3183-3c0f-4f04-85e6-ed40283265a5',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118.
  $menu_links['main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118',
    'router_path' => 'uuid',
    'link_title' => 'Pricing Table',
    'options' => array(
      'identifier' => 'main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'e54ed492-aa67-4f17-84c2-a841dac84118',
    'vuuid' => '83500693-693b-4c88-8b81-bfbbf7c97e09',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_pull-down-box-header:uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e.
  $menu_links['main-menu_pull-down-box-header:uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e',
    'router_path' => 'uuid',
    'link_title' => 'Pull-Down Box Header',
    'options' => array(
      'identifier' => 'main-menu_pull-down-box-header:uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e',
    'vuuid' => '7757011a-6077-4ba0-a64e-90eac1cf77ce',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c.
  $menu_links['main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/d495cf25-fc13-4103-a876-c71b190c421c',
    'router_path' => 'uuid',
    'link_title' => 'Quote Slider',
    'options' => array(
      'identifier' => 'main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => 'd495cf25-fc13-4103-a876-c71b190c421c',
    'vuuid' => '4f7d1603-e7fc-4478-a8cb-9701a1876740',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_registration-landing-1:uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0.
  $menu_links['main-menu_registration-landing-1:uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0',
    'router_path' => 'uuid',
    'link_title' => 'Registration Landing 1',
    'options' => array(
      'identifier' => 'main-menu_registration-landing-1:uuid/node/73824210-432e-4f4d-b0e8-4cc1866bb6b0',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '73824210-432e-4f4d-b0e8-4cc1866bb6b0',
    'vuuid' => '9377af4f-8a4b-4166-b4b1-e479777e9127',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_registration-landing-2:uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33.
  $menu_links['main-menu_registration-landing-2:uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33',
    'router_path' => 'uuid',
    'link_title' => 'Registration Landing 2',
    'options' => array(
      'identifier' => 'main-menu_registration-landing-2:uuid/node/f33609ac-acba-4168-ba00-0f56d82e8b33',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'f33609ac-acba-4168-ba00-0f56d82e8b33',
    'vuuid' => '27340a48-c5e9-4d9b-8baf-6d00ea135e34',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_restaurant-menu-page:uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba.
  $menu_links['main-menu_restaurant-menu-page:uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba',
    'router_path' => 'uuid',
    'link_title' => 'Restaurant Menu Page',
    'options' => array(
      'identifier' => 'main-menu_restaurant-menu-page:uuid/node/9ddaf86c-5040-4a76-986a-cd6621deacba',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '9ddaf86c-5040-4a76-986a-cd6621deacba',
    'vuuid' => '70439614-2086-4ca1-8ddd-2963532d6fcd',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1.
  $menu_links['main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    'router_path' => 'uuid',
    'link_title' => 'Revolution Slider',
    'options' => array(
      'identifier' => 'main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    'vuuid' => 'ab04aca3-f63b-4216-b763-b49600b5c144',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed.
  $menu_links['main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    'router_path' => 'uuid',
    'link_title' => 'Sections and Backgrounds',
    'options' => array(
      'identifier' => 'main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '969e7879-63f5-464c-a8af-6fb131a1aeed',
    'vuuid' => '875efc99-a907-463f-a744-cd065e7af8be',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_services-page:uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814.
  $menu_links['main-menu_services-page:uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814',
    'router_path' => 'uuid',
    'link_title' => 'Services Page',
    'options' => array(
      'identifier' => 'main-menu_services-page:uuid/node/e31a7eb7-7117-45c3-ad3f-91f8c6589814',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'e31a7eb7-7117-45c3-ad3f-91f8c6589814',
    'vuuid' => '54d47fcc-bf0f-4458-b5b6-7f4adae82578',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_side-header:uuid/node/2666ca79-fd85-4457-8a13-133e93db3693.
  $menu_links['main-menu_side-header:uuid/node/2666ca79-fd85-4457-8a13-133e93db3693'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2666ca79-fd85-4457-8a13-133e93db3693',
    'router_path' => 'uuid',
    'link_title' => 'Side Header',
    'options' => array(
      'identifier' => 'main-menu_side-header:uuid/node/2666ca79-fd85-4457-8a13-133e93db3693',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '2666ca79-fd85-4457-8a13-133e93db3693',
    'vuuid' => 'f0f329de-2281-4354-a929-3cb3b0388248',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364.
  $menu_links['main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/887edc90-eb66-4e94-9757-645e9221a364',
    'router_path' => 'uuid',
    'link_title' => 'Social Links',
    'options' => array(
      'identifier' => 'main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '887edc90-eb66-4e94-9757-645e9221a364',
    'vuuid' => '114c354d-3293-4039-b554-cc317745ce8d',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a.
  $menu_links['main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'router_path' => 'uuid',
    'link_title' => 'Tabs',
    'options' => array(
      'identifier' => 'main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'vuuid' => '5f3b7c97-55c4-4949-b4ff-b2a602078c48',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6.
  $menu_links['main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6',
    'router_path' => 'uuid',
    'link_title' => 'Team Box',
    'options' => array(
      'identifier' => 'main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '706f5a68-da75-4834-a050-9de1b4d58fd6',
    'vuuid' => '5f4048a4-3f2b-40c3-af34-ef2bb6045e88',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_team-page:uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308.
  $menu_links['main-menu_team-page:uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308',
    'router_path' => 'uuid',
    'link_title' => 'Team Page',
    'options' => array(
      'identifier' => 'main-menu_team-page:uuid/node/ef10c794-ab7b-4983-9c72-c59899b4a308',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => 'ef10c794-ab7b-4983-9c72-c59899b4a308',
    'vuuid' => 'edee9679-8abc-45cd-a910-6a5352bb0f4e',
    'parent_identifier' => 'main-menu_pages:events',
  );
  // Exported menu link: main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093.
  $menu_links['main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    'router_path' => 'uuid',
    'link_title' => 'Time Line',
    'options' => array(
      'identifier' => 'main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'b50ca955-ea53-4854-a408-6f39a7262093',
    'vuuid' => '80740ac9-943b-4f02-9410-420624cb4dcc',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_transparent-header:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71.
  $menu_links['main-menu_transparent-header:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    'router_path' => 'uuid',
    'link_title' => 'Transparent Header',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_transparent-header:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '51bb3421-2cc2-42b4-b278-5e845db02e71',
    'vuuid' => '1f892124-120f-4ffd-8f73-5bf4815ac91a',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c.
  $menu_links['main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'router_path' => 'uuid',
    'link_title' => 'Video Element',
    'options' => array(
      'identifier' => 'main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'vuuid' => 'ece5eb5a-2680-494f-8721-bfe60da3f5ae',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192.
  $menu_links['main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'router_path' => 'uuid',
    'link_title' => 'Well',
    'options' => array(
      'identifier' => 'main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => 'ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'vuuid' => 'b45b36a8-4f8e-4dab-9c32-69d7ed59dbee',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('About Me');
  t('About Us');
  t('About Us Timeline');
  t('Animation Engine');
  t('Blockquote');
  t('Blog');
  t('Blog Classic Style');
  t('Blog Grid 2 Columns');
  t('Blog Grid 3 Columns');
  t('Blog Grid 4 Columns');
  t('Blog GridStack');
  t('Blog Modern Style');
  t('Box Header');
  t('Buttons');
  t('Call to Action');
  t('Carousel Element');
  t('Centered (Inline)');
  t('Centered (Stacked)');
  t('Circle Counter');
  t('Collapsibles');
  t('Colored Icon Boxes');
  t('Columns');
  t('Contact');
  t('Content Elements');
  t('Count Down Timer');
  t('Counter');
  t('Custom Colors');
  t('Details Bottom');
  t('Details Left');
  t('Details Right');
  t('Divider');
  t('Drop Shadow');
  t('Drupal Blocks');
  t('Drupal Views');
  t('Elements');
  t('Events');
  t('FAQ');
  t('Floating Menu Header');
  t('Full Width Header');
  t('Glazed Filter No Spacing');
  t('Glazed Filter With Spacing');
  t('Glazed Full Screen Modal Portfolio');
  t('Glazed Inline Modal Portfolio');
  t('Glazed Lightbox Portfolio');
  t('Google Maps');
  t('Grid Portfolio');
  t('GridStack View');
  t('Header Layouts');
  t('Header Styles');
  t('Headers');
  t('Home App Landing Page');
  t('Home Basic');
  t('Home Blog Classic');
  t('Home Business Clean');
  t('Home Canvas');
  t('Home Main Demo');
  t('Homepage Portfolio 1');
  t('Homepages');
  t('Icon Box');
  t('Icon Well');
  t('Icons');
  t('Image Compare');
  t('Image Element & Slider');
  t('Interactive Elements');
  t('Jumbotron');
  t('Layout Elements');
  t('Lead');
  t('Lightbox Images');
  t('Logo Center, Menu Left');
  t('Logo Center, Menu Right');
  t('Logo Left, Menu Left');
  t('Logo Right, Menu Left');
  t('Masonry Portfolio');
  t('Media Elements');
  t('Motion Image Box');
  t('News');
  t('Pages');
  t('Panel');
  t('Portfolio');
  t('Portfolio 1 Column');
  t('Portfolio 1 Column with Excerpt');
  t('Portfolio 2 Columns');
  t('Portfolio 3 Columns');
  t('Portfolio 4 Columns');
  t('Portfolio 6 Columns');
  t('Portfolio Masonry 2');
  t('Portfolio Masonry 2 with Excerpt');
  t('Portfolio Masonry 3');
  t('Portfolio Masonry 3 with Excerpt');
  t('Portfolio Masonry 4');
  t('Portfolio Masonry 4 with Excerpt');
  t('Portfolio Masonry 6');
  t('Portfolio Pages');
  t('Positioned Layers');
  t('Premium Portfolio');
  t('Pricing Page');
  t('Pricing Table');
  t('Pull-Down Box Header');
  t('Quote Slider');
  t('Registration Landing 1');
  t('Registration Landing 2');
  t('Restaurant Menu Page');
  t('Revolution Slider');
  t('Sections and Backgrounds');
  t('Services Page');
  t('Side Header');
  t('Social Links');
  t('Tabs');
  t('Team Box');
  t('Team Page');
  t('Time Line');
  t('Transparent Header');
  t('Video Element');
  t('Well');

  return $menu_links;
}
