<?php
/**
 * @file
 * glazed_content_elements_examples_2.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_content_elements_examples_2_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc.
  $menu_links['main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    'router_path' => 'uuid',
    'link_title' => 'Animation Engine',
    'options' => array(
      'identifier' => 'main-menu_animation-engine:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '34998698-bc3b-4056-a6b6-b793443a2edc',
    'vuuid' => '84cea0ee-1965-479c-8d62-77bfa76bf503',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea.
  $menu_links['main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea',
    'router_path' => 'uuid',
    'link_title' => 'Call to Action',
    'options' => array(
      'identifier' => 'main-menu_call-to-action:uuid/node/a13b4055-cfd9-4437-9127-35acd06cf9ea',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'a13b4055-cfd9-4437-9127-35acd06cf9ea',
    'vuuid' => '95815eaa-9829-4a95-963d-47454312b70d',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f.
  $menu_links['main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    'router_path' => 'uuid',
    'link_title' => 'Circle Counter',
    'options' => array(
      'identifier' => 'main-menu_circle-counter:uuid/node/5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '5c9b6810-6a1f-4109-9a8b-2560f5c65d0f',
    'vuuid' => '1810f3be-24d2-4a36-8623-2685793a7d8d',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829.
  $menu_links['main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9e718e9f-d297-46a8-a908-142b3853d829',
    'router_path' => 'uuid',
    'link_title' => 'Count Down Timer',
    'options' => array(
      'identifier' => 'main-menu_count-down-timer:uuid/node/9e718e9f-d297-46a8-a908-142b3853d829',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '9e718e9f-d297-46a8-a908-142b3853d829',
    'vuuid' => 'f3234817-0792-478e-a0cf-1e87597d205c',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33.
  $menu_links['main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    'router_path' => 'uuid',
    'link_title' => 'Counter',
    'options' => array(
      'identifier' => 'main-menu_counter:uuid/node/9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '9c1a0b9b-a4c6-4c74-b134-975d2f0c0f33',
    'vuuid' => '917171ce-c179-46c1-b729-7a0d4fb38ceb',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640.
  $menu_links['main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640',
    'router_path' => 'uuid',
    'link_title' => 'Drop Shadow',
    'options' => array(
      'identifier' => 'main-menu_drop-shadow:uuid/node/88d22be5-b9e3-4953-b98b-9c2deac33640',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '88d22be5-b9e3-4953-b98b-9c2deac33640',
    'vuuid' => '04b1f346-629f-42b9-b984-0de7da9f7483',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4.
  $menu_links['main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/621b040c-215e-4302-a133-ee52589bf8c4',
    'router_path' => 'uuid',
    'link_title' => 'Drupal Blocks',
    'options' => array(
      'identifier' => 'main-menu_drupal-blocks:uuid/node/621b040c-215e-4302-a133-ee52589bf8c4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '621b040c-215e-4302-a133-ee52589bf8c4',
    'vuuid' => 'b08f63c7-eb36-4590-8c89-1ad822d48f89',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d.
  $menu_links['main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d',
    'router_path' => 'uuid',
    'link_title' => 'Drupal Views',
    'options' => array(
      'identifier' => 'main-menu_drupal-views:uuid/node/8a6234be-e970-4c98-8074-daeda9957d3d',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '8a6234be-e970-4c98-8074-daeda9957d3d',
    'vuuid' => 'c4128650-0e0d-4970-a157-2c387f8522b4',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32.
  $menu_links['main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32',
    'router_path' => 'uuid',
    'link_title' => 'Google Maps',
    'options' => array(
      'identifier' => 'main-menu_google-maps:uuid/node/a4608e7f-a620-4b47-b9a6-3e960302cf32',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a4608e7f-a620-4b47-b9a6-3e960302cf32',
    'vuuid' => '2d4ed853-275d-4130-8baf-af6117d9a432',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598.
  $menu_links['main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    'router_path' => 'uuid',
    'link_title' => 'Icons',
    'options' => array(
      'identifier' => 'main-menu_icons:uuid/node/4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '4b2cf32d-ba09-4ba9-9879-5a9bd359b598',
    'vuuid' => '06577404-6f00-48bd-8e91-8f52859c8add',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94.
  $menu_links['main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    'router_path' => 'uuid',
    'link_title' => 'Image Element & Slider',
    'options' => array(
      'identifier' => 'main-menu_image-element--slider:uuid/node/0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '0d2550e9-bc2f-42f7-9f4a-27f5ad950b94',
    'vuuid' => 'f8f0268c-6a3c-4d53-95ac-225dbc4c134f',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc.
  $menu_links['main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    'router_path' => 'uuid',
    'link_title' => 'Interactive Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '34998698-bc3b-4056-a6b6-b793443a2edc',
    'vuuid' => '84cea0ee-1965-479c-8d62-77bfa76bf503',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c.
  $menu_links['main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'router_path' => 'uuid',
    'link_title' => 'Media Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'vuuid' => '5e873eb9-0f73-447e-81d8-614dc3ed96d3',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456.
  $menu_links['main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456',
    'router_path' => 'uuid',
    'link_title' => 'Motion Image Box',
    'options' => array(
      'identifier' => 'main-menu_motion-image-box:uuid/node/448c021f-1d62-43a3-aaa9-6111e2dca456',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '448c021f-1d62-43a3-aaa9-6111e2dca456',
    'vuuid' => 'eadeb3b8-f10f-4f51-8ff0-71107e050126',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118.
  $menu_links['main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118',
    'router_path' => 'uuid',
    'link_title' => 'Pricing Table',
    'options' => array(
      'identifier' => 'main-menu_pricing-table:uuid/node/e54ed492-aa67-4f17-84c2-a841dac84118',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'e54ed492-aa67-4f17-84c2-a841dac84118',
    'vuuid' => '985dafaa-79ef-44bd-9894-e38e6c8bece0',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c.
  $menu_links['main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/d495cf25-fc13-4103-a876-c71b190c421c',
    'router_path' => 'uuid',
    'link_title' => 'Quote Slider',
    'options' => array(
      'identifier' => 'main-menu_quote-slider:uuid/node/d495cf25-fc13-4103-a876-c71b190c421c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => 'd495cf25-fc13-4103-a876-c71b190c421c',
    'vuuid' => '715b1f84-f4d1-42ec-b639-2e0f25564d60',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1.
  $menu_links['main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    'router_path' => 'uuid',
    'link_title' => 'Revolution Slider',
    'options' => array(
      'identifier' => 'main-menu_revolution-slider:uuid/node/1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '1a7f1fac-caa4-42b6-8c3e-46fef3fc12e1',
    'vuuid' => '8efa56d4-23d0-4ee8-b3c7-351138e32bf0',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364.
  $menu_links['main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/887edc90-eb66-4e94-9757-645e9221a364',
    'router_path' => 'uuid',
    'link_title' => 'Social Links',
    'options' => array(
      'identifier' => 'main-menu_social-links:uuid/node/887edc90-eb66-4e94-9757-645e9221a364',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '887edc90-eb66-4e94-9757-645e9221a364',
    'vuuid' => '6ff3df36-15fd-4dfb-b476-6e00b15aa49e',
    'parent_identifier' => 'main-menu_interactive-elements:uuid/node/34998698-bc3b-4056-a6b6-b793443a2edc',
  );
  // Exported menu link: main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6.
  $menu_links['main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6',
    'router_path' => 'uuid',
    'link_title' => 'Team Box',
    'options' => array(
      'identifier' => 'main-menu_team-box:uuid/node/706f5a68-da75-4834-a050-9de1b4d58fd6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '706f5a68-da75-4834-a050-9de1b4d58fd6',
    'vuuid' => 'a59531c9-57aa-47a3-bcf7-7efab92269db',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );
  // Exported menu link: main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c.
  $menu_links['main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'router_path' => 'uuid',
    'link_title' => 'Video Element',
    'options' => array(
      'identifier' => 'main-menu_video-element:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '90e2fdb0-fe08-47e2-8ea5-4e844154920c',
    'vuuid' => '5e873eb9-0f73-447e-81d8-614dc3ed96d3',
    'parent_identifier' => 'main-menu_media-elements:uuid/node/90e2fdb0-fe08-47e2-8ea5-4e844154920c',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Animation Engine');
  t('Call to Action');
  t('Circle Counter');
  t('Count Down Timer');
  t('Counter');
  t('Drop Shadow');
  t('Drupal Blocks');
  t('Drupal Views');
  t('Google Maps');
  t('Icons');
  t('Image Element & Slider');
  t('Interactive Elements');
  t('Media Elements');
  t('Motion Image Box');
  t('Pricing Table');
  t('Quote Slider');
  t('Revolution Slider');
  t('Social Links');
  t('Team Box');
  t('Video Element');

  return $menu_links;
}
