<?php
/**
 * @file
 * cms_events_content.features.uuid_file_entity.inc
 */

/**
 * Implements hook_uuid_features_default_file_entities().
 */
function cms_events_content_uuid_features_default_file_entities() {
  $files = array();

  $files[] = array(
    'filename' => 'photo-1492541737557-dfd592c6e42d.jpg',
    'uri' => 'public://photo-1492541737557-dfd592c6e42d.jpg',
    'filemime' => 'image/jpeg',
    'status' => 1,
    'type' => 'image',
    'uuid' => '05b672db-b9d6-471d-83f3-91409ede1767',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 3588,
      'width' => 5382,
    ),
    'alt' => '',
    'title' => '',
    'height' => 3588,
    'width' => 5382,
    'uuid_features_packaged_file_path' => 'assets/photo-1492541737557-dfd592c6e42d.jpg',
    'user_uuid' => 'f885e99c-38f2-4357-aa91-449eca11029c',
  );
  $files[] = array(
    'filename' => 'photo-1492538368677-f6e0afe31dcc.jpg',
    'uri' => 'public://photo-1492538368677-f6e0afe31dcc.jpg',
    'filemime' => 'image/jpeg',
    'status' => 1,
    'type' => 'image',
    'uuid' => '7f0776fd-d360-4e5e-bb33-c6d65e8484f9',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 2625,
      'width' => 3937,
    ),
    'alt' => '',
    'title' => '',
    'height' => 2625,
    'width' => 3937,
    'uuid_features_packaged_file_path' => 'assets/photo-1492538368677-f6e0afe31dcc.jpg',
    'user_uuid' => 'f885e99c-38f2-4357-aa91-449eca11029c',
  );
  $files[] = array(
    'filename' => 'photo-1477281765962-ef34e8bb0967.jpg',
    'uri' => 'public://photo-1477281765962-ef34e8bb0967.jpg',
    'filemime' => 'image/jpeg',
    'status' => 1,
    'type' => 'image',
    'uuid' => 'c4dc3b6c-b233-4b02-ac09-2b0c4f14c293',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 4000,
      'width' => 5049,
    ),
    'alt' => '',
    'title' => '',
    'height' => 4000,
    'width' => 5049,
    'uuid_features_packaged_file_path' => 'assets/photo-1477281765962-ef34e8bb0967.jpg',
    'user_uuid' => 'f885e99c-38f2-4357-aa91-449eca11029c',
  );
  return $files;
}
