<?php
/**
 * @file
 * glazed_content_elements_examples_1.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_content_elements_examples_1_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0.
  $menu_links['main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'router_path' => 'uuid',
    'link_title' => 'Blockquote',
    'options' => array(
      'identifier' => 'main-menu_blockquote:uuid/node/229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => '229435b1-1c29-4eab-a591-9c8ceaaff8a0',
    'vuuid' => 'f9f74d20-5a3b-4323-a361-7100d535fbe5',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb.
  $menu_links['main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    'router_path' => 'uuid',
    'link_title' => 'Buttons',
    'options' => array(
      'identifier' => 'main-menu_buttons:uuid/node/34d13068-3849-4eaf-89d4-880954ac8bdb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => '34d13068-3849-4eaf-89d4-880954ac8bdb',
    'vuuid' => 'f9364eb5-cb9a-4512-8744-4a8e72151195',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Carousel Element',
    'options' => array(
      'identifier' => 'main-menu_carousel-element:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => '8a8ff068-a1d4-4f13-9db9-77c577fdfbe6',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99.
  $menu_links['main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'router_path' => 'uuid',
    'link_title' => 'Collapsibles',
    'options' => array(
      'identifier' => 'main-menu_collapsibles:uuid/node/5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '5b9b97a8-bb26-4288-a08e-5c4891a1fe99',
    'vuuid' => '2dc67156-281d-4625-8689-148c8ac675be',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92.
  $menu_links['main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    'router_path' => 'uuid',
    'link_title' => 'Colored Icon Boxes',
    'options' => array(
      'identifier' => 'main-menu_colored-icon-boxes:uuid/node/4e840855-52c9-47a4-9f74-80fb2734dd92',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '4e840855-52c9-47a4-9f74-80fb2734dd92',
    'vuuid' => '305dc03d-7b62-47d3-816c-69fd926c8f09',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a.
  $menu_links['main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'router_path' => 'uuid',
    'link_title' => 'Columns',
    'options' => array(
      'identifier' => 'main-menu_columns:uuid/node/c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'c3b6b1cf-1ae1-48ad-ab3a-0287775fe14a',
    'vuuid' => '1a3db38d-2475-44bb-8bd8-ce8381b713d5',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb.
  $menu_links['main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'router_path' => 'uuid',
    'link_title' => 'Content Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'vuuid' => '297c6d7b-ddc9-4edc-9137-7bb66b586088',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd.
  $menu_links['main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    'router_path' => 'uuid',
    'link_title' => 'Divider',
    'options' => array(
      'identifier' => 'main-menu_divider:uuid/node/0825174b-b312-41f9-b2f6-64d4c22edefd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '0825174b-b312-41f9-b2f6-64d4c22edefd',
    'vuuid' => '175d2c92-115b-4ad7-bb62-ac617fcc614c',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Elements',
    'options' => array(
      'identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => '8a8ff068-a1d4-4f13-9db9-77c577fdfbe6',
  );
  // Exported menu link: main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b.
  $menu_links['main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'router_path' => 'uuid',
    'link_title' => 'GridStack View',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_gridstack-view:uuid/node/06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '06f8b908-96a6-4fb1-a7a6-d443b8ed2f1b',
    'vuuid' => '2b9c15ed-4676-4558-8999-21bf6f26699d',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb.
  $menu_links['main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'router_path' => 'uuid',
    'link_title' => 'Icon Box',
    'options' => array(
      'identifier' => 'main-menu_icon-box:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
    'vuuid' => '297c6d7b-ddc9-4edc-9137-7bb66b586088',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd.
  $menu_links['main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    'router_path' => 'uuid',
    'link_title' => 'Icon Well',
    'options' => array(
      'identifier' => 'main-menu_icon-well:uuid/node/5ff84c19-e9e1-4760-9253-abbedce064cd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '5ff84c19-e9e1-4760-9253-abbedce064cd',
    'vuuid' => 'd3ac0f61-f476-499d-b466-acde0e0b506c',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2.
  $menu_links['main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'router_path' => 'uuid',
    'link_title' => 'Jumbotron',
    'options' => array(
      'identifier' => 'main-menu_jumbotron:uuid/node/bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'bfb6a4e5-3557-489b-b949-872f6dd0ebb2',
    'vuuid' => '21200ed8-97e2-4dad-a420-d43e7f0726d4',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4.
  $menu_links['main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'router_path' => 'uuid',
    'link_title' => 'Layout Elements',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'cef1e560-174e-4387-b0a9-82c592ff8ed4',
    'vuuid' => '8a8ff068-a1d4-4f13-9db9-77c577fdfbe6',
    'parent_identifier' => 'main-menu_elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7.
  $menu_links['main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'router_path' => 'uuid',
    'link_title' => 'Lead',
    'options' => array(
      'identifier' => 'main-menu_lead:uuid/node/9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'uuid' => '9e0ff233-9546-4277-bac0-a2e6cb36c8a7',
    'vuuid' => 'c2f585ae-9795-464a-bd19-161da628465b',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902.
  $menu_links['main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'router_path' => 'uuid',
    'link_title' => 'Panel',
    'options' => array(
      'identifier' => 'main-menu_panel:uuid/node/2e6d0201-12ac-40ce-8c42-15b8251b7902',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '2e6d0201-12ac-40ce-8c42-15b8251b7902',
    'vuuid' => '8fdc4505-39a4-4294-a597-1cab4f5754fa',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e.
  $menu_links['main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'router_path' => 'uuid',
    'link_title' => 'Positioned Layers',
    'options' => array(
      'identifier' => 'main-menu_positioned-layers:uuid/node/a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a5fc2ec5-7d47-40cb-98c3-50916154e18e',
    'vuuid' => '205e7eca-60a8-473f-9272-1e5ff2f78e1a',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed.
  $menu_links['main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    'router_path' => 'uuid',
    'link_title' => 'Sections and Backgrounds',
    'options' => array(
      'identifier' => 'main-menu_sections-and-backgrounds:uuid/node/969e7879-63f5-464c-a8af-6fb131a1aeed',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '969e7879-63f5-464c-a8af-6fb131a1aeed',
    'vuuid' => '407a8985-b964-4fd0-94b8-fc54b8b7e7c7',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a.
  $menu_links['main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'router_path' => 'uuid',
    'link_title' => 'Tabs',
    'options' => array(
      'identifier' => 'main-menu_tabs:uuid/node/92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '92e308f2-1208-4b67-ba2b-04dbe2d5833a',
    'vuuid' => 'b9f637ca-a432-4643-a690-72e749281ebf',
    'parent_identifier' => 'main-menu_content-elements:uuid/node/8cee9fbf-2933-45e5-9c12-b6aab9075cfb',
  );
  // Exported menu link: main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093.
  $menu_links['main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    'router_path' => 'uuid',
    'link_title' => 'Time Line',
    'options' => array(
      'identifier' => 'main-menu_time-line:uuid/node/b50ca955-ea53-4854-a408-6f39a7262093',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'b50ca955-ea53-4854-a408-6f39a7262093',
    'vuuid' => '973dfde0-3f52-4bbf-ae0a-bc042b72fd1a',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );
  // Exported menu link: main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192.
  $menu_links['main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'router_path' => 'uuid',
    'link_title' => 'Well',
    'options' => array(
      'identifier' => 'main-menu_well:uuid/node/ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'uuid' => 'ca2e52f4-ec41-4a6b-ae81-6aeef8149192',
    'vuuid' => '95eba0eb-fe83-4745-8419-893086b0416c',
    'parent_identifier' => 'main-menu_layout-elements:uuid/node/cef1e560-174e-4387-b0a9-82c592ff8ed4',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Blockquote');
  t('Buttons');
  t('Carousel Element');
  t('Collapsibles');
  t('Colored Icon Boxes');
  t('Columns');
  t('Content Elements');
  t('Divider');
  t('Elements');
  t('GridStack View');
  t('Icon Box');
  t('Icon Well');
  t('Jumbotron');
  t('Layout Elements');
  t('Lead');
  t('Panel');
  t('Positioned Layers');
  t('Sections and Backgrounds');
  t('Tabs');
  t('Time Line');
  t('Well');

  return $menu_links;
}
