<?php
/**
 * @file
 * glazed_content_homepage_examples.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_content_homepage_examples_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917.
  $menu_links['main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'router_path' => 'uuid',
    'link_title' => 'Home App Landing Page',
    'options' => array(
      'identifier' => 'main-menu_home-app-landing-page:uuid/node/a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a32afdd3-e3b0-4afb-9b9d-fca4ee53e917',
    'vuuid' => 'd05901a4-742b-4a90-92da-f4c6bb044789',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6.
  $menu_links['main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'router_path' => 'uuid',
    'link_title' => 'Home Basic',
    'options' => array(
      'identifier' => 'main-menu_home-basic:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'vuuid' => '3414de34-5b3f-4cf5-b7e2-58b19e6c2e96',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35.
  $menu_links['main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'router_path' => 'uuid',
    'link_title' => 'Home Blog Classic',
    'options' => array(
      'identifier' => 'main-menu_home-blog-classic:uuid/node/703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '703a60cd-2aa6-42ae-8ef9-cb207933bf35',
    'vuuid' => '0970000a-ab60-4be4-a902-9c16ce784d8d',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825.
  $menu_links['main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    'router_path' => 'uuid',
    'link_title' => 'Home Business Clean',
    'options' => array(
      'identifier' => 'main-menu_home-business-clean:uuid/node/760f2195-e3fd-4957-ac92-410530f39825',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => '760f2195-e3fd-4957-ac92-410530f39825',
    'vuuid' => '30b2149e-b56c-4982-82ca-29b5ab313664',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd.
  $menu_links['main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    'router_path' => 'uuid',
    'link_title' => 'Home Canvas',
    'options' => array(
      'identifier' => 'main-menu_home-canvas:uuid/node/2bc7e0bd-0597-455f-9730-a058acce07dd',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '2bc7e0bd-0597-455f-9730-a058acce07dd',
    'vuuid' => '2fff4c8c-8d30-4465-9564-59464b4ac769',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4.
  $menu_links['main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    'router_path' => 'uuid',
    'link_title' => 'Home Main Demo',
    'options' => array(
      'identifier' => 'main-menu_home-main-demo:uuid/node/c8982be9-90c8-4813-ad2d-87c0934213e4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => 'c8982be9-90c8-4813-ad2d-87c0934213e4',
    'vuuid' => 'ce9f1ef0-d03d-40b2-a4d0-2efff86b8ef8',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_homepage-portfolio-1:uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf.
  $menu_links['main-menu_homepage-portfolio-1:uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf',
    'router_path' => 'uuid',
    'link_title' => 'Homepage Portfolio 1',
    'options' => array(
      'identifier' => 'main-menu_homepage-portfolio-1:uuid/node/f58f6881-0aef-4492-ad3b-c03be4cc29cf',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'f58f6881-0aef-4492-ad3b-c03be4cc29cf',
    'vuuid' => '66c71638-091c-42d1-a3e0-a5f7fd78a96b',
    'parent_identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
  );
  // Exported menu link: main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6.
  $menu_links['main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'router_path' => 'uuid',
    'link_title' => 'Homepages',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_homepages:uuid/node/fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'fc35b67a-3cea-4e3b-bfc7-17018413f4d6',
    'vuuid' => '3414de34-5b3f-4cf5-b7e2-58b19e6c2e96',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Home App Landing Page');
  t('Home Basic');
  t('Home Blog Classic');
  t('Home Business Clean');
  t('Home Canvas');
  t('Home Main Demo');
  t('Homepage Portfolio 1');
  t('Homepages');

  return $menu_links;
}
