<?php
/**
 * @file
 * glazed_content_header_examples.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function glazed_content_header_examples_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_box-header:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73.
  $menu_links['main-menu_box-header:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    'router_path' => 'uuid',
    'link_title' => 'Box Header',
    'options' => array(
      'identifier' => 'main-menu_box-header:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'f9deb576-445f-4b2b-914b-930fc84dcf73',
    'vuuid' => '9bd78979-fb27-4f6a-9fc0-f6292f633dda',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_centered-inline:uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4.
  $menu_links['main-menu_centered-inline:uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4',
    'router_path' => 'uuid',
    'link_title' => 'Centered (Inline)',
    'options' => array(
      'identifier' => 'main-menu_centered-inline:uuid/node/cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => 'cb5d554f-9ba6-4d78-9d5c-cb7cb4819be4',
    'vuuid' => '50c49d50-932b-4a4a-9694-b30e8aeecaea',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_centered-stacked:uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50.
  $menu_links['main-menu_centered-stacked:uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50',
    'router_path' => 'uuid',
    'link_title' => 'Centered (Stacked)',
    'options' => array(
      'identifier' => 'main-menu_centered-stacked:uuid/node/2efc8ede-fe27-42f4-b1a9-aa20c164ab50',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'uuid' => '2efc8ede-fe27-42f4-b1a9-aa20c164ab50',
    'vuuid' => '5f552854-f548-41de-8f72-7e0b5f32bec8',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_custom-colors:uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4.
  $menu_links['main-menu_custom-colors:uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4',
    'router_path' => 'uuid',
    'link_title' => 'Custom Colors',
    'options' => array(
      'identifier' => 'main-menu_custom-colors:uuid/node/c52c1f98-2302-4133-9d8c-811d45a7f4b4',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'uuid' => 'c52c1f98-2302-4133-9d8c-811d45a7f4b4',
    'vuuid' => '39406d74-7a83-45f0-abe6-2eb42e8357f3',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_floating-menu-header:uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56.
  $menu_links['main-menu_floating-menu-header:uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56',
    'router_path' => 'uuid',
    'link_title' => 'Floating Menu Header',
    'options' => array(
      'identifier' => 'main-menu_floating-menu-header:uuid/node/a5b033a1-c69c-4bc0-b645-23a0658efb56',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => 'a5b033a1-c69c-4bc0-b645-23a0658efb56',
    'vuuid' => '95c5760a-f271-4677-aaf2-aca8ad1bc5bf',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_full-width-header:uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac.
  $menu_links['main-menu_full-width-header:uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac',
    'router_path' => 'uuid',
    'link_title' => 'Full Width Header',
    'options' => array(
      'identifier' => 'main-menu_full-width-header:uuid/node/2b1a92c8-69d9-494b-8db2-d588f8a012ac',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'uuid' => '2b1a92c8-69d9-494b-8db2-d588f8a012ac',
    'vuuid' => 'ca4bc2b4-e9f6-46e8-a488-c757ab5ab0c0',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095.
  $menu_links['main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    'router_path' => 'uuid',
    'link_title' => 'Header Layouts',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '7288000a-d02b-4ffa-96df-0029ffcfc095',
    'vuuid' => '7f099b96-763e-45ef-9779-a8c3be6c4ba5',
    'parent_identifier' => 'main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
  );
  // Exported menu link: main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73.
  $menu_links['main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    'router_path' => 'uuid',
    'link_title' => 'Header Styles',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'uuid' => 'f9deb576-445f-4b2b-914b-930fc84dcf73',
    'vuuid' => '9bd78979-fb27-4f6a-9fc0-f6292f633dda',
    'parent_identifier' => 'main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
  );
  // Exported menu link: main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71.
  $menu_links['main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    'router_path' => 'uuid',
    'link_title' => 'Headers',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_headers:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '51bb3421-2cc2-42b4-b278-5e845db02e71',
    'vuuid' => 'f97066af-0aa7-4fcd-86c2-fb75ec6daccb',
  );
  // Exported menu link: main-menu_logo-center-menu-left:uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648.
  $menu_links['main-menu_logo-center-menu-left:uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648',
    'router_path' => 'uuid',
    'link_title' => 'Logo Center, Menu Left',
    'options' => array(
      'identifier' => 'main-menu_logo-center-menu-left:uuid/node/8c1594e4-5a78-4657-b6dc-26b40cf72648',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '8c1594e4-5a78-4657-b6dc-26b40cf72648',
    'vuuid' => '2154b6f9-b3be-4ad9-b232-26493fe9669e',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_logo-center-menu-right:uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5.
  $menu_links['main-menu_logo-center-menu-right:uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5',
    'router_path' => 'uuid',
    'link_title' => 'Logo Center, Menu Right',
    'options' => array(
      'identifier' => 'main-menu_logo-center-menu-right:uuid/node/f62f6d64-0a66-4d18-bbdc-692f0a946ac5',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'uuid' => 'f62f6d64-0a66-4d18-bbdc-692f0a946ac5',
    'vuuid' => '0ebcc13f-1313-41e4-89bd-953923f2669f',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_logo-left-menu-left:uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b.
  $menu_links['main-menu_logo-left-menu-left:uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b',
    'router_path' => 'uuid',
    'link_title' => 'Logo Left, Menu Left',
    'options' => array(
      'identifier' => 'main-menu_logo-left-menu-left:uuid/node/0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'uuid' => '0e51456a-cf62-4c5d-9d6b-ebfb9dd2577b',
    'vuuid' => '7d691542-5194-4213-a010-e771a64d8975',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_logo-right-menu-left:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095.
  $menu_links['main-menu_logo-right-menu-left:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    'router_path' => 'uuid',
    'link_title' => 'Logo Right, Menu Left',
    'options' => array(
      'identifier' => 'main-menu_logo-right-menu-left:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '7288000a-d02b-4ffa-96df-0029ffcfc095',
    'vuuid' => '7f099b96-763e-45ef-9779-a8c3be6c4ba5',
    'parent_identifier' => 'main-menu_header-layouts:uuid/node/7288000a-d02b-4ffa-96df-0029ffcfc095',
  );
  // Exported menu link: main-menu_pull-down-box-header:uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e.
  $menu_links['main-menu_pull-down-box-header:uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e',
    'router_path' => 'uuid',
    'link_title' => 'Pull-Down Box Header',
    'options' => array(
      'identifier' => 'main-menu_pull-down-box-header:uuid/node/0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'uuid' => '0cf51090-8d6a-4e4f-8fb7-7c9d6c6b655e',
    'vuuid' => '46427d0d-a0e9-4e2e-a3cf-47d5b9ec7aca',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_side-header:uuid/node/2666ca79-fd85-4457-8a13-133e93db3693.
  $menu_links['main-menu_side-header:uuid/node/2666ca79-fd85-4457-8a13-133e93db3693'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/2666ca79-fd85-4457-8a13-133e93db3693',
    'router_path' => 'uuid',
    'link_title' => 'Side Header',
    'options' => array(
      'identifier' => 'main-menu_side-header:uuid/node/2666ca79-fd85-4457-8a13-133e93db3693',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'uuid' => '2666ca79-fd85-4457-8a13-133e93db3693',
    'vuuid' => '3c2de041-fe6b-49cd-8506-833edebed5c0',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );
  // Exported menu link: main-menu_transparent-header:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71.
  $menu_links['main-menu_transparent-header:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    'router_path' => 'uuid',
    'link_title' => 'Transparent Header',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_transparent-header:uuid/node/51bb3421-2cc2-42b4-b278-5e845db02e71',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'uuid' => '51bb3421-2cc2-42b4-b278-5e845db02e71',
    'vuuid' => 'f97066af-0aa7-4fcd-86c2-fb75ec6daccb',
    'parent_identifier' => 'main-menu_header-styles:uuid/node/f9deb576-445f-4b2b-914b-930fc84dcf73',
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Box Header');
  t('Centered (Inline)');
  t('Centered (Stacked)');
  t('Custom Colors');
  t('Floating Menu Header');
  t('Full Width Header');
  t('Header Layouts');
  t('Header Styles');
  t('Headers');
  t('Logo Center, Menu Left');
  t('Logo Center, Menu Right');
  t('Logo Left, Menu Left');
  t('Logo Right, Menu Left');
  t('Pull-Down Box Header');
  t('Side Header');
  t('Transparent Header');

  return $menu_links;
}
