<?php
/**
 * @file
 * glazed_content_header_examples.features.uuid_field_collection.inc
 */

/**
 * Implements hook_uuid_features_default_field_collections().
 */
function glazed_content_header_examples_uuid_features_default_field_collections() {
  $field_collections = array();

  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '09d096ec-9275-486a-b43b-934fd8c3d75c',
    'field_dropdown_background' => array(),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'side',
        ),
      ),
    ),
    'field_glazed_header_position' => array(),
    'field_glazed_header_style' => array(),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(),
    'field_header_text' => array(),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(
      'und' => array(
        0 => array(
          'value' => 'background',
        ),
      ),
    ),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(),
    'field_page_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'fullwidth',
        ),
      ),
    ),
    'field_side_header_background' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_side_header_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#696969',
          'format' => NULL,
        ),
      ),
    ),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '30210fad-9afa-4b09-8c36-d84e615d8312',
    'field_dropdown_background' => array(),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(),
    'field_glazed_header_style' => array(),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'centered_inline',
        ),
      ),
    ),
    'field_header_text' => array(),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '3a359960-12d9-4de6-b4e6-69630e2b7fe5',
    'field_dropdown_background' => array(
      'und' => array(
        0 => array(
          'value' => '#f3f3f3',
          'format' => NULL,
        ),
      ),
    ),
    'field_dropdown_hover_background' => array(
      'und' => array(
        0 => array(
          'value' => '#f3f3f3',
          'format' => NULL,
        ),
      ),
    ),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_header_style' => array(
      'und' => array(
        0 => array(
          'value' => 'navbar_pull_down',
        ),
      ),
    ),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(
      'und' => array(
        0 => array(
          'value' => 'white',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_background' => array(
      'und' => array(
        0 => array(
          'value' => 'silver#f3f3f3',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'logo_left_menu_right',
        ),
      ),
    ),
    'field_header_text' => array(),
    'field_menu_background' => array(
      'und' => array(
        0 => array(
          'value' => '#f3f3f3',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(
      'und' => array(
        0 => array(
          'value' => '#f3f3f3',
          'format' => NULL,
        ),
      ),
    ),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '3a6ee47f-a933-4e36-bea5-1896e6c50e4c',
    'field_dropdown_background' => array(
      'und' => array(
        0 => array(
          'value' => 'rgba(0,0,0,0.7);',
          'format' => NULL,
        ),
      ),
    ),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(
      'und' => array(
        0 => array(
          'value' => 'fullwidth',
        ),
      ),
    ),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(
      'und' => array(
        0 => array(
          'value' => 'fixed',
        ),
      ),
    ),
    'field_glazed_header_style' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(
      'und' => array(
        0 => array(
          'value' => 'rgba(0,0,0,0.3)',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_height' => array(),
    'field_header_layout' => array(),
    'field_header_text' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_navbar_background' => array(),
    'field_page_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'fullwidth',
        ),
      ),
    ),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '5a2d84f4-f700-49b0-b70d-43791b2ea1d8',
    'field_dropdown_background' => array(
      'und' => array(
        0 => array(
          'value' => 'rgba(0,0,0,0.85);',
          'format' => NULL,
        ),
      ),
    ),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_header_style' => array(
      'und' => array(
        0 => array(
          'value' => 'overlay',
        ),
      ),
    ),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'page_title',
        ),
        1 => array(
          'value' => 'sidebar_first',
        ),
        2 => array(
          'value' => 'sidebar_second',
        ),
      ),
    ),
    'field_header_background' => array(
      'und' => array(
        0 => array(
          'value' => 'transparent',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(
      'und' => array(
        0 => array(
          'value' => 'white',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_height' => array(),
    'field_header_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'centered',
        ),
      ),
    ),
    'field_header_text' => array(
      'und' => array(
        0 => array(
          'value' => 'white',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(
      'und' => array(
        0 => array(
          'value' => 'transparent',
          'format' => NULL,
        ),
      ),
    ),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '7c9b9ac9-f7df-43e6-817f-206dfefe3ca8',
    'field_dropdown_background' => array(),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(),
    'field_glazed_header_position' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_header_style' => array(
      'und' => array(
        0 => array(
          'value' => 'overlay',
        ),
      ),
    ),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(
      'und' => array(
        0 => array(
          'value' => 'transparent',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(),
    'field_header_text' => array(),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(
      'und' => array(
        0 => array(
          'value' => 'white',
          'format' => NULL,
        ),
      ),
    ),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '98d71b30-00b4-4120-8db0-489489bb486d',
    'field_dropdown_background' => array(),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(),
    'field_glazed_header_style' => array(),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'logo_left_menu_left',
        ),
      ),
    ),
    'field_header_text' => array(),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => '9aed5260-2dac-416e-a13c-7db95495937c',
    'field_dropdown_background' => array(
      'und' => array(
        0 => array(
          'value' => 'rgba(0,0,0,0.7);',
          'format' => NULL,
        ),
      ),
    ),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_header_style' => array(
      'und' => array(
        0 => array(
          'value' => 'overlay',
        ),
      ),
    ),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(
      'und' => array(
        0 => array(
          'value' => 'transparent',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_height' => array(),
    'field_header_layout' => array(),
    'field_header_text' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(
      'und' => array(
        0 => array(
          'value' => 'opacity',
        ),
      ),
    ),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_navbar_background' => array(),
    'field_page_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'fullwidth',
        ),
      ),
    ),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => 'a121db4a-5e8f-42c6-b798-150b8d1eabd1',
    'field_dropdown_background' => array(
      'und' => array(
        0 => array(
          'value' => '#3e2c2c',
          'format' => NULL,
        ),
      ),
    ),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(),
    'field_glazed_header_style' => array(
      'und' => array(
        0 => array(
          'value' => 'overlay',
        ),
      ),
    ),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(
      'und' => array(
        0 => array(
          'value' => 'transparent',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_background' => array(
      'und' => array(
        0 => array(
          'value' => '#c32231',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_height' => array(
      'und' => array(
        0 => array(
          'value' => 80,
          'format' => NULL,
        ),
      ),
    ),
    'field_header_layout' => array(),
    'field_header_text' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_background' => array(
      'und' => array(
        0 => array(
          'value' => '#3e2c2c',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_hover_background' => array(
      'und' => array(
        0 => array(
          'value' => '#c32231',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_hover_effect' => array(
      'und' => array(
        0 => array(
          'value' => 'border',
        ),
      ),
    ),
    'field_menu_hover_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_navbar_background' => array(
      'und' => array(
        0 => array(
          'value' => '#3e2c2c',
          'format' => NULL,
        ),
      ),
    ),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => 'ab033898-20b6-4db3-9d41-032129cf3fbf',
    'field_dropdown_background' => array(
      'und' => array(
        0 => array(
          'value' => '#333',
          'format' => NULL,
        ),
      ),
    ),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(
      'und' => array(
        0 => array(
          'value' => 'normal',
        ),
      ),
    ),
    'field_glazed_header_style' => array(
      'und' => array(
        0 => array(
          'value' => 'overlay',
        ),
      ),
    ),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(
      'und' => array(
        0 => array(
          'value' => 'transparent',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_background' => array(
      'und' => array(
        0 => array(
          'value' => '#F99138',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_block_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_header_height' => array(
      'und' => array(
        0 => array(
          'value' => 60,
          'format' => NULL,
        ),
      ),
    ),
    'field_header_layout' => array(),
    'field_header_text' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_background' => array(
      'und' => array(
        0 => array(
          'value' => '#333',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_hover_background' => array(
      'und' => array(
        0 => array(
          'value' => '#F99138',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_menu_text_color' => array(
      'und' => array(
        0 => array(
          'value' => '#fff',
          'format' => NULL,
        ),
      ),
    ),
    'field_navbar_background' => array(
      'und' => array(
        0 => array(
          'value' => 'transparent',
          'format' => NULL,
        ),
      ),
    ),
    'field_page_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'fullwidth',
        ),
      ),
    ),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => 'd5f6c7fa-9663-43b4-ab9e-dbd229f93f00',
    'field_dropdown_background' => array(),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(
      'und' => array(
        0 => array(
          'value' => 'fullwidth',
        ),
      ),
    ),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(),
    'field_glazed_header_style' => array(),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'logo_center_menu_left',
        ),
      ),
    ),
    'field_header_text' => array(),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => 'dfd05d65-00f3-4e6f-92f5-b087f6892ad8',
    'field_dropdown_background' => array(),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(
      'und' => array(
        0 => array(
          'value' => 'fullwidth',
        ),
      ),
    ),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(),
    'field_glazed_header_style' => array(),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'logo_center_menu_right',
        ),
      ),
    ),
    'field_header_text' => array(),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  $field_collections[] = array(
    'field_name' => 'field_glazed_content_design',
    'default_revision' => 1,
    'archived' => 0,
    'uuid' => 'f9f22153-c14f-447c-b856-88dd3f9c965d',
    'field_dropdown_background' => array(),
    'field_dropdown_hover_background' => array(),
    'field_dropdown_hover_text_color' => array(),
    'field_dropdown_text_color' => array(),
    'field_full_width_header' => array(),
    'field_glazed_body_image' => array(),
    'field_glazed_content_region' => array(),
    'field_glazed_header_image' => array(),
    'field_glazed_header_mode' => array(
      'und' => array(
        0 => array(
          'value' => 'top',
        ),
      ),
    ),
    'field_glazed_header_position' => array(),
    'field_glazed_header_style' => array(),
    'field_glazed_hide_regions' => array(
      'und' => array(
        0 => array(
          'value' => 'secondary_header',
        ),
        1 => array(
          'value' => 'page_title',
        ),
      ),
    ),
    'field_header_background' => array(),
    'field_header_block_background' => array(),
    'field_header_block_text_color' => array(),
    'field_header_height' => array(),
    'field_header_layout' => array(
      'und' => array(
        0 => array(
          'value' => 'logo_right_menu_left',
        ),
      ),
    ),
    'field_header_text' => array(),
    'field_menu_background' => array(),
    'field_menu_hover_background' => array(),
    'field_menu_hover_effect' => array(),
    'field_menu_hover_text_color' => array(),
    'field_menu_text_color' => array(),
    'field_navbar_background' => array(),
    'field_page_layout' => array(),
    'field_side_header_background' => array(),
    'field_side_header_text_color' => array(),
    'field_side_header_width' => array(),
    'rdf_mapping' => array(),
  );
  return $field_collections;
}
