<?php
/**
 * @file
 * glazed_content_header_examples.features.uuid_file_entity.inc
 */

/**
 * Implements hook_uuid_features_default_file_entities().
 */
function glazed_content_header_examples_uuid_features_default_file_entities() {
  $files = array();

  $files[] = array(
    'filename' => 'buddhist-monks-elephant-1920.jpg',
    'uri' => 'public://page-cb_attachments/buddhist-monks-elephant-1920.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 399137,
    'status' => 1,
    'type' => 'image',
    'uuid' => '4ba7006f-9a6d-43ae-92f7-d41ff2b2c348',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'alt' => '',
    'title' => '',
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/buddhist-monks-elephant-1920.jpg',
    'user_uuid' => '06421791-c291-4c51-8e56-3aa1519fd98f',
  );
  $files[] = array(
    'filename' => 'clean-desk-top_1.jpg',
    'uri' => 'public://page-cb_attachments/clean-desk-top_1.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 400188,
    'status' => 1,
    'type' => 'image',
    'uuid' => '4da2a0dc-e1be-46c4-b312-62e05964d34c',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1225,
      'width' => 1920,
    ),
    'alt' => '',
    'title' => '',
    'height' => 1225,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/clean-desk-top_1.jpg',
    'user_uuid' => '06421791-c291-4c51-8e56-3aa1519fd98f',
  );
  $files[] = array(
    'filename' => 'casual-professional_0.jpg',
    'uri' => 'public://page-cb_attachments/casual-professional_0.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 143559,
    'status' => 1,
    'type' => 'image',
    'uuid' => '75b687d0-a898-49c6-b87e-336f13462d71',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1112,
      'width' => 1920,
    ),
    'alt' => '',
    'title' => '',
    'height' => 1112,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/casual-professional_0.jpg',
    'user_uuid' => '06421791-c291-4c51-8e56-3aa1519fd98f',
  );
  $files[] = array(
    'filename' => 'demopagesB.jpg',
    'uri' => 'public://page-cb_attachments/demopagesB.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 751302,
    'status' => 1,
    'type' => 'image',
    'uuid' => '82ed31a3-2613-4eef-823e-0c86077905d8',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1272,
      'width' => 1920,
    ),
    'alt' => '',
    'title' => '',
    'height' => 1272,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/demopagesB.jpg',
    'user_uuid' => '06421791-c291-4c51-8e56-3aa1519fd98f',
  );
  $files[] = array(
    'filename' => 'demopages-32.jpg',
    'uri' => 'public://page-cb_attachments/demopages-32.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 614041,
    'status' => 1,
    'type' => 'image',
    'uuid' => '9ee1042d-33c1-4d28-8488-b9076b0bed37',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1200,
      'width' => 1920,
    ),
    'alt' => '',
    'title' => '',
    'height' => 1200,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/demopages-32.jpg',
    'user_uuid' => '06421791-c291-4c51-8e56-3aa1519fd98f',
  );
  $files[] = array(
    'filename' => 'food-hero-adnan-puzic-hq-1-1920.jpg',
    'uri' => 'public://page-cb_attachments/food-hero-adnan-puzic-hq-1-1920.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 672752,
    'status' => 1,
    'type' => 'image',
    'uuid' => 'b9359b64-78f8-4ff9-bc92-47b86705373e',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1286,
      'width' => 1920,
    ),
    'alt' => '',
    'title' => '',
    'height' => 1286,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/food-hero-adnan-puzic-hq-1-1920.jpg',
    'user_uuid' => '06421791-c291-4c51-8e56-3aa1519fd98f',
  );
  $files[] = array(
    'filename' => 'cupcake-redshift.jpg',
    'uri' => 'public://page-cb_attachments/cupcake-redshift.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 379323,
    'status' => 1,
    'type' => 'image',
    'uuid' => 'ccfc2df1-7d42-457b-9818-4f48169f8e6c',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1280,
      'width' => 1920,
    ),
    'alt' => '',
    'title' => '',
    'height' => 1280,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/cupcake-redshift.jpg',
    'user_uuid' => '06421791-c291-4c51-8e56-3aa1519fd98f',
  );
  return $files;
}
